test /health case 1

diff --git a/.github/workflows/http-status-check.yml b/.github/workflows/http-status-check.yml
--- a/.github/workflows/http-status-check.yml
+++ b/.github/workflows/http-status-check.yml
@@ -42,10 +42,10 @@ jobs:
         run: /home/runner/go/bin/templ generate -path ${{ matrix.framework }}
 
       # - if : ${{ matrix.driver == 'none' && matrix.advanced != 'htmx' && matrix.advanced != 'websocket' && matrix.advanced != 'githubaction' }}
-      - name: Test /health Endpoints
+      - name: Test / Endpoints
         run: |
           cd ${{ matrix.framework }}
-          make run &
+          make run
           sleep 5
           STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" localhost:8080)
           if [ $STATUS_CODE -ne 200 ]; then
@@ -53,3 +53,16 @@ jobs:
             exit 1
           fi
       
+      - if : ${{ matrix.driver != 'none' }}
+        name: Test / health Endpoints
+        run: |
+          cd ${{ matrix.framework }}
+          make run
+          sleep 5
+          make docker-run
+          sleep 15
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" localhost:8080/health)
+          if [ $STATUS_CODE -ne 200 ]; then
+            echo "Error: Non-200 status code received ($STATUS_CODE)"
+            exit 1
+          fi
