test / all cases

diff --git a/.github/workflows/http-status-check.yml b/.github/workflows/http-status-check.yml
--- a/.github/workflows/http-status-check.yml
+++ b/.github/workflows/http-status-check.yml
@@ -50,3 +50,15 @@ jobs:
             echo "Error: Non-200 status code received ($STATUS_CODE)"
             exit 1
           fi
+
+      # - if : ${{ matrix.driver == 'none' && matrix.advanced != 'htmx' && matrix.advanced != 'websocket' && matrix.advanced != 'githubaction' }}
+      - name: Test /health Endpoints
+        run: |
+          make run
+          make docker-run
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" localhost:8080)
+          if [ $STATUS_CODE -ne 200 ]; then
+            echo "Error: Non-200 status code received ($STATUS_CODE)"
+            exit 1
+          fi
+      
